config/routes.rb
Rails.application.routes.draw do
  root to: 'tweets#index'
  resources :tweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  def self.sync(query)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['TWITTER_API_KEY']
      config.consumer_secret     = ENV['TWITTER_API_SECRET']
      config.access_token        = ENV['TWITTER_ACCESS_TOKEN']
      config.access_token_secret = ENV['TWITTER_ACCESS_TOKEN_SECRET']
    end

    created = []

    client.search("#{query} -rt").first(500).each do |tweet|
      created << create(body: tweet.text, query: query)
    end


    created.sort_by(&:score).reverse!
  end

  before_save :set_sentiment, if: :body_changed?

  scope :positive, ->{ where(sentiment: :positive) }
  scope :negative, ->{ where(sentiment: :negative) }
  scope :neutral, ->{ where(sentiment: :neutral) }
  scope :scored, ->{ where('score != 0') }

  def set_sentiment
    self.sentiment = $analyzer.sentiment(body)
    self.score = $analyzer.score(body)
  end

  def avg_score
    scores = Tweet.where(query: query).map(&:score)
    scores.reduce(&:+) / scores.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    Tweet.sync(params[:query]) if params[:query].present?
    @tweets = Tweet.scored.paginate(page: params[:page], per_page: 50)

    respond_to do |format|
      format.html { render 'tweets/index' }
      format.js
    end
  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def edit
  end

  def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new
    end
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy

    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:body, :sentiment, :score, :query)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= favicon_link_tag asset_path('http://www.iconarchive.com/download/i82970/limav/flat-gradient-social/Twitter.ico') %>
    <title>TweetAnalyzer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </body>
</html>

app/views/tweets/_tweet_partial.html.erb
<% @tweets.each do |tweet| %>
  <tr class='tweet-info'>
    <td><%= tweet.body %></td>
    <td><%= tweet.sentiment %></td>
    <% if tweet.score > 0.5 %>
      <td>
        <i class="fas fa-thumbs-up" id='thumb-up'></i>
        <%= tweet.score %>
      </td>
    <% else %>
      <td>
        <i class="fas fa-thumbs-down" id='thumb-down'></i>
        <%= tweet.score %>
      </td>
    <% end %>
    <td><%= link_to tweet.query, tweet_path(tweet) %></td>
  </tr>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>


<%= form_tag(tweets_path, method: :get, remote: true) do %>
  <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Get tweets on topic" %>
<% end %>

<h1>Search twitter for sentiments on a topic</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Sentiment</th>
      <th>Score</th>
      <th>Query</th>
    </tr>
  </thead>

  <tbody id='tweets' class='infinite-scroll'>
    <%= render 'tweet_partial' %>
  </tbody>
</table>

<br>
<div id="paginator">
  <%= will_paginate @tweets %>
</div>

app/views/tweets/index.js.erb
function addTweets(reviewHTML) {
  const tweets = document.getElementById('tweets');
  tweets.innerHTML = null;
  tweets.insertAdjacentHTML('afterEnd', reviewHTML);
}

addTweets('<%= j render "tweets/tweet_partial" %>');

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @tweet.body %>
</p>

<p>
  <strong>Sentiment:</strong>
  <%= @tweet.sentiment %>
</p>

<p>
  <strong>Score:</strong>
  <%= @tweet.score %>
</p>

<p>
  <strong>Average score for <%= @tweet.query %></strong>
  <%= @tweet.avg_score %>
</p>

<%= link_to 'Back', tweets_path %>